// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyExample_web_api_key',
    appId: '1:123456789012:web:abcdef123456789',
    messagingSenderId: '123456789012',
    projectId: 'supermarket-system-placeholder',
    authDomain: 'supermarket-system-placeholder.firebaseapp.com',
    storageBucket: 'supermarket-system-placeholder.appspot.com',
    measurementId: 'G-EXAMPLE12345',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyExample_android_api_key',
    appId: '1:123456789012:android:abcdef123456789',
    messagingSenderId: '123456789012',
    projectId: 'supermarket-system-placeholder',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyExample_ios_api_key',
    appId: '1:123456789012:ios:abcdef123456789',
    messagingSenderId: '123456789012',
    projectId: 'supermarket-system-placeholder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyExample_macos_api_key',
    appId: '1:123456789012:macos:abcdef123456789',
    messagingSenderId: '123456789012',
    projectId: 'supermarket-system-placeholder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyExample_windows_api_key',
    appId: '1:123456789012:windows:abcdef123456789',
    messagingSenderId: '123456789012',
    projectId: 'supermarket-system-placeholder',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyExample_linux_api_key',
    appId: '1:123456789012:linux:abcdef123456789',
    messagingSenderId: '123456789012',
    projectId: 'supermarket-system-placeholder',
  );
}